from setuptools import setup, find_packages

setup(
    name="bce-prediction-server",
    version="1.0.0",
    description="B-cell Epitope Prediction Server using ReCEP model",
    author="BCE Team",
    author_email="contact@bce-prediction.com",
    url="https://github.com/YitaoXU/ReCEP",
    packages=find_packages(),
    install_requires=[
        "gradio>=4.44.0",
        "numpy>=1.26.4",
        "pandas>=2.1.4",
        "torch>=2.0.0",
        "biotite>=0.41.2",
        "biopython>=1.85",
        "h5py>=3.9.0",
        "scipy>=1.13.0",
        "scikit-learn>=1.5.2",
        "tqdm>=4.67.1",
        "matplotlib>=3.9.3",
        "seaborn>=0.13.2",
        "py3Dmol>=2.4.2",
        "prettytable>=3.16.0",
        "cloudpathlib>=0.16.0",
        "requests>=2.31.0",
        "pillow>=10.1.0",
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0",
        "python-multipart>=0.0.6",
        "jinja2>=3.1.2",
        "aiofiles>=23.2.1",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords="bioinformatics protein epitope prediction machine-learning",
    entry_points={
        "console_scripts": [
            "bce-server=app:main",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
